version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://dastanbaitursynov:infinitiq502.0t@db:5432/betmaker
      - SECRET_KEY=deirubviuewrbnvlorwiubnoveb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dastanbaitursynov
      - POSTGRES_PASSWORD=infinitiq502.0t
      - POSTGRES_DB=betmaker

volumes:
  postgres_data: